repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3  # можно обновлять
    hooks:
      - id: ruff-format
        files: ^backend/
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: pytest-backend
        name: pytest_backend
        entry: bash -c "cd backend && source .venv/bin/activate && pytest tests/"
        language: system
        pass_filenames: false
        stages: [pre-push]